[project]
name = "image_vectorizer"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "opencv-python",
    "Pillow",
    "numpy>=1.26.0",
    "fonttools",
    "svgpathtools",
    "svgwrite"
]
